package database

// 會話與審計——baseline schema 的「audit」域（migration-baseline-compression D1）。
//
// 會話與其指令／剪貼簿留存、審計日誌鏈、告警與審閱。
//
// **DDL 一律無條件**（不使用任何條件式建立語法）：baseline 是全新安裝的唯一 schema 事實源，
// 在非空 schema 上跑必須立刻炸而不是靜默 no-op——後者正是 2026-08-12 索引事故的成因。
//
// 本檔為機器可讀的最終形狀宣告，不描述任何歷史演進；欄位語義見對應的
// internal/model 檔與 docs/DB_SCHEMA.md。

// baselineAuditTables 本域的建表 DDL（依「被參照者先建」排列）。
var baselineAuditTables = []string{
	`CREATE TABLE sessions (
		id bigserial,
		created_at timestamp with time zone,
		updated_at timestamp with time zone,
		deleted_at timestamp with time zone,
		session_id character varying(100) NOT NULL,
		status character varying(20) NOT NULL,
		protocol character varying(10) NOT NULL,
		user_id bigint NOT NULL,
		asset_id bigint,
		client_ip character varying(50),
		start_time timestamp with time zone,
		end_time timestamp with time zone,
		duration bigint,
		end_reason character varying(20) DEFAULT 'normal'::character varying,
		recording_path character varying(500),
		recording_size bigint,
		has_recording boolean DEFAULT false,
		recording_error text,
		recording_started_at timestamp with time zone,
		account_id bigint,
		account_username character varying(100),
		auth_provider_id bigint,
		auth_epoch bigint DEFAULT 0 NOT NULL,
		k8s_namespace character varying(63),
		k8s_pod character varying(253),
		k8s_pod_uid character varying(40),
		k8s_container character varying(63),
		k8s_image character varying(255),
		k8s_node character varying(253),
		CONSTRAINT sessions_pkey PRIMARY KEY (id)
	)`,
	`CREATE TABLE session_commands (
		id bigserial,
		session_id bigint NOT NULL,
		user_id bigint NOT NULL,
		asset_id bigint,
		command text NOT NULL,
		seq integer NOT NULL,
		executed_at timestamp with time zone NOT NULL,
		degraded boolean DEFAULT false NOT NULL,
		degrade_reason character varying(64) DEFAULT ''::character varying NOT NULL,
		k8s_pod character varying(253) DEFAULT ''::character varying NOT NULL,
		k8s_container character varying(63) DEFAULT ''::character varying NOT NULL,
		CONSTRAINT session_commands_pkey PRIMARY KEY (id),
		CONSTRAINT session_commands_degraded_no_text CHECK ((NOT degraded) OR (command = ''::text))
	)`,
	`CREATE TABLE clipboard_events (
		id bigserial,
		session_id bigint NOT NULL,
		direction character varying(8) NOT NULL,
		content text,
		created_at timestamp with time zone,
		CONSTRAINT clipboard_events_pkey PRIMARY KEY (id)
	)`,
	`CREATE TABLE transmission_consents (
		id bigserial,
		created_at timestamp with time zone,
		updated_at timestamp with time zone,
		user_id bigint NOT NULL,
		asset_id bigint NOT NULL,
		risk_fingerprint character varying(64) NOT NULL,
		risk_items text NOT NULL,
		consented_at timestamp with time zone NOT NULL,
		CONSTRAINT transmission_consents_pkey PRIMARY KEY (id)
	)`,
	`CREATE TABLE audit_logs (
		id bigserial,
		created_at timestamp with time zone,
		updated_at timestamp with time zone,
		deleted_at timestamp with time zone,
		action character varying(20) NOT NULL,
		resource character varying(20) NOT NULL,
		resource_id bigint,
		status character varying(20) NOT NULL,
		asset_id bigint,
		user_id bigint NOT NULL,
		username character varying(100) NOT NULL,
		method character varying(10),
		path character varying(500),
		client_ip character varying(50),
		status_code bigint,
		duration bigint,
		request_body text,
		error_msg text,
		details text,
		request_id character varying(100),
		idempotency_uuid character varying(64),
		integrity_hmac character varying(64),
		key_version bigint DEFAULT 0 NOT NULL,
		CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
	)`,
	`CREATE TABLE audit_checkpoints (
		id bigserial,
		seq bigint NOT NULL,
		id_from bigint NOT NULL,
		id_to bigint NOT NULL,
		row_count bigint NOT NULL,
		agg_hash character varying(64) NOT NULL,
		agg_scheme character varying(32) NOT NULL,
		prev_checkpoint_hash character varying(64) NOT NULL,
		min_created_at timestamp with time zone,
		max_created_at timestamp with time zone,
		sealed_at timestamp with time zone NOT NULL,
		signing_key_version bigint NOT NULL,
		signature character varying(128) NOT NULL,
		anchor_status character varying(16) NOT NULL,
		purged_at timestamp with time zone,
		purge_signature character varying(128),
		purge_signing_key_version bigint,
		purge_policy_days bigint,
		created_at timestamp with time zone,
		CONSTRAINT audit_checkpoints_pkey PRIMARY KEY (id)
	)`,
	`CREATE TABLE audit_checkpoint_trims (
		id bigserial,
		from_seq bigint NOT NULL,
		last_trimmed_seq bigint NOT NULL,
		trimmed_count bigint NOT NULL,
		last_trimmed_link_hash character varying(64) NOT NULL,
		genesis_id_from bigint NOT NULL,
		policy_days bigint NOT NULL,
		trimmed_at timestamp with time zone NOT NULL,
		signing_key_version bigint NOT NULL,
		signature character varying(128) NOT NULL,
		created_at timestamp with time zone,
		CONSTRAINT audit_checkpoint_trims_pkey PRIMARY KEY (id)
	)`,
	`CREATE TABLE audit_chain_verify_states (
		id bigserial,
		recent_last_run_at timestamp with time zone,
		recent_last_status character varying(16) DEFAULT ''::character varying NOT NULL,
		recent_last_duration_ms bigint DEFAULT 0 NOT NULL,
		recent_window_days_effective bigint DEFAULT 0 NOT NULL,
		recent_last_seq bigint DEFAULT 0 NOT NULL,
		full_last_run_at timestamp with time zone,
		full_last_status character varying(16) DEFAULT ''::character varying NOT NULL,
		full_last_duration_ms bigint DEFAULT 0 NOT NULL,
		structure_failed_count bigint DEFAULT 0 NOT NULL,
		content_verified_intervals bigint DEFAULT 0 NOT NULL,
		content_cursor_seq bigint DEFAULT 0 NOT NULL,
		last_full_cycle_at timestamp with time zone,
		open_failed_seqs text DEFAULT ''::text NOT NULL,
		last_fingerprint character varying(32) DEFAULT ''::character varying NOT NULL,
		updated_at timestamp with time zone,
		CONSTRAINT audit_chain_verify_states_pkey PRIMARY KEY (id)
	)`,
	`CREATE TABLE audit_failure_events (
		id bigserial,
		mechanism character varying(30) NOT NULL,
		started_at timestamp with time zone NOT NULL,
		ended_at timestamp with time zone,
		cause text NOT NULL,
		cause_code character varying(64) DEFAULT ''::character varying NOT NULL,
		cause_params text DEFAULT ''::text NOT NULL,
		details text,
		created_at timestamp with time zone,
		updated_at timestamp with time zone,
		CONSTRAINT audit_failure_events_pkey PRIMARY KEY (id)
	)`,
	`CREATE TABLE audit_retention_watermarks (
		id bigserial,
		class character varying(32) NOT NULL,
		purged_through_at timestamp with time zone NOT NULL,
		last_purge_at timestamp with time zone NOT NULL,
		policy_days bigint,
		partial boolean DEFAULT false NOT NULL,
		updated_at timestamp with time zone,
		CONSTRAINT audit_retention_watermarks_pkey PRIMARY KEY (id)
	)`,
	`CREATE TABLE integrity_baselines (
		id bigserial,
		baseline_at timestamp with time zone NOT NULL,
		max_log_id bigint DEFAULT 0 NOT NULL,
		CONSTRAINT integrity_baselines_pkey PRIMARY KEY (id)
	)`,
	`CREATE TABLE daily_review_logs (
		id bigserial,
		review_date character varying(10) NOT NULL,
		reviewer_id bigint NOT NULL,
		reviewer_name character varying(100) NOT NULL,
		snapshot_json text NOT NULL,
		note text,
		created_at timestamp with time zone,
		CONSTRAINT daily_review_logs_pkey PRIMARY KEY (id)
	)`,
	`CREATE TABLE alert_rules (
		id bigserial,
		name character varying(100) NOT NULL,
		pattern text NOT NULL,
		severity character varying(10) NOT NULL,
		enabled boolean DEFAULT true NOT NULL,
		created_at timestamp with time zone DEFAULT now() NOT NULL,
		updated_at timestamp with time zone DEFAULT now() NOT NULL,
		action character varying(10) DEFAULT 'alert'::character varying NOT NULL,
		protocols character varying(64) DEFAULT ''::character varying NOT NULL,
		CONSTRAINT alert_rules_action_check CHECK (action IN ('alert','block')),
		CONSTRAINT alert_rules_severity_check CHECK (severity IN ('high','medium','low')),
		CONSTRAINT alert_rules_pkey PRIMARY KEY (id)
	)`,
	`CREATE TABLE command_alerts (
		id bigserial,
		rule_id bigint,
		rule_name character varying(100) NOT NULL,
		session_id bigint NOT NULL,
		user_id bigint NOT NULL,
		asset_id bigint,
		command text NOT NULL,
		severity character varying(10) NOT NULL,
		triggered_at timestamp with time zone NOT NULL,
		reviewed_by bigint,
		reviewed_at timestamp with time zone,
		disposition character varying(20) DEFAULT 'pending'::character varying NOT NULL,
		note text DEFAULT ''::text NOT NULL,
		blocked boolean DEFAULT false NOT NULL,
		kind character varying(20) DEFAULT 'rule'::character varying NOT NULL,
		reason_code character varying(64) DEFAULT ''::character varying NOT NULL,
		CONSTRAINT command_alerts_severity_check CHECK (severity IN ('high','medium','low')),
		CONSTRAINT command_alerts_kind_check CHECK (kind IN ('rule','audit_degraded')),
		CONSTRAINT command_alerts_kind_rule_ref CHECK ((kind = 'rule') = (rule_id IS NOT NULL)),
		CONSTRAINT command_alerts_pkey PRIMARY KEY (id)
	)`,
}

// baselineAuditForeignKeys 本域的外鍵約束（於全部建表之後統一套用，故不受建表順序限制）。
var baselineAuditForeignKeys = []string{
	`ALTER TABLE sessions ADD CONSTRAINT fk_sessions_asset FOREIGN KEY (asset_id) REFERENCES assets(id)`,
	`ALTER TABLE sessions ADD CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id)`,
}

// baselineAuditIndexes 本域的索引。
var baselineAuditIndexes = []string{
	`CREATE INDEX idx_sessions_account_id ON sessions USING btree (account_id)`,
	`CREATE INDEX idx_sessions_asset_start ON sessions USING btree (asset_id, start_time)`,
	`CREATE INDEX idx_sessions_auth_provider_id ON sessions USING btree (auth_provider_id)`,
	`CREATE INDEX idx_sessions_deleted_at ON sessions USING btree (deleted_at)`,
	`CREATE UNIQUE INDEX idx_sessions_session_id ON sessions USING btree (session_id)`,
	`CREATE INDEX idx_sessions_user_start ON sessions USING btree (user_id, start_time)`,
	`CREATE INDEX idx_session_commands_asset_executed ON session_commands USING btree (asset_id, executed_at)`,
	`CREATE INDEX idx_session_commands_session_seq ON session_commands USING btree (session_id, seq)`,
	`CREATE INDEX idx_session_commands_user_executed ON session_commands USING btree (user_id, executed_at)`,
	`CREATE INDEX idx_session_commands_user_id ON session_commands USING btree (user_id)`,
	`CREATE INDEX idx_clipboard_events_session_id ON clipboard_events USING btree (session_id)`,
	`CREATE UNIQUE INDEX idx_consent_user_asset ON transmission_consents USING btree (user_id, asset_id)`,
	`CREATE INDEX idx_transmission_consents_asset_id ON transmission_consents USING btree (asset_id)`,
	`CREATE INDEX idx_audit_action_status ON audit_logs USING btree (action, status)`,
	`CREATE INDEX idx_audit_asset_created ON audit_logs USING btree (asset_id, created_at)`,
	`CREATE INDEX idx_audit_client_ip ON audit_logs USING btree (client_ip)`,
	`CREATE INDEX idx_audit_created_at ON audit_logs USING btree (created_at)`,
	`CREATE UNIQUE INDEX idx_audit_idempotency ON audit_logs USING btree (idempotency_uuid)`,
	`CREATE INDEX idx_audit_logs_deleted_at ON audit_logs USING btree (deleted_at)`,
	`CREATE INDEX idx_audit_request_id ON audit_logs USING btree (request_id)`,
	`CREATE INDEX idx_audit_resource ON audit_logs USING btree (resource, resource_id)`,
	`CREATE INDEX idx_audit_user_created ON audit_logs USING btree (user_id, created_at)`,
	`CREATE INDEX idx_audit_checkpoints_range ON audit_checkpoints USING btree (id_from, id_to)`,
	`CREATE UNIQUE INDEX idx_audit_checkpoints_seq ON audit_checkpoints USING btree (seq)`,
	`CREATE UNIQUE INDEX idx_checkpoint_trims_last_seq ON audit_checkpoint_trims USING btree (last_trimmed_seq)`,
	`CREATE UNIQUE INDEX idx_failure_events_single_open ON audit_failure_events USING btree (mechanism) WHERE (ended_at IS NULL)`,
	`CREATE INDEX idx_failure_mechanism_open ON audit_failure_events USING btree (mechanism, ended_at)`,
	`CREATE UNIQUE INDEX idx_retention_watermark_class ON audit_retention_watermarks USING btree (class)`,
	`CREATE UNIQUE INDEX idx_daily_review_logs_review_date ON daily_review_logs USING btree (review_date)`,
	`CREATE UNIQUE INDEX uniq_alert_rules_name ON alert_rules (name)`,
	`CREATE INDEX idx_command_alerts_asset_triggered ON command_alerts USING btree (asset_id, triggered_at)`,
	`CREATE INDEX idx_command_alerts_severity ON command_alerts USING btree (severity)`,
	`CREATE INDEX idx_command_alerts_triggered_at ON command_alerts USING btree (triggered_at DESC)`,
	`CREATE INDEX idx_command_alerts_unreviewed ON command_alerts USING btree (triggered_at DESC) WHERE (reviewed_at IS NULL)`,
	`CREATE INDEX idx_command_alerts_user_triggered ON command_alerts USING btree (user_id, triggered_at)`,
}
