package middleware

// AgentRouteDecision is an explicit method + registered Gin path ledger. Unknown
// routes are denied at runtime and fail coverage in the server guard. Report and
// MCP entries reserve their contract categories; they do not register handlers.
// Asset reads are metadata and pod listings, never file contents/downloads.
func AgentRouteDecision(method, path string) (allowed, registered bool) {
	switch method + " " + path {
	case "GET /api/v1/agent-tasks/:requestId", "GET /api/v1/agent-tasks", "GET /api/v1/users/:id/agent-breaker/events":
		return false, true
	case "GET /api/v1/my/agents", "POST /api/v1/my/agents":
		return false, true
	case "GET /api/v1/access-requests/mine":
		return true, true
	case "GET /api/v1/access-requests/mine/tickets":
		return true, true
	case "GET /api/v1/assets":
		return true, true
	case "GET /api/v1/assets/:id":
		return true, true
	case "GET /api/v1/assets/:id/accounts":
		return true, true
	case "GET /api/v1/assets/:id/k8s/pods":
		return true, true
	case "GET /api/v1/assets/tags":
		return true, true
	case "GET /api/v1/my/connections":
		return true, true
	case "POST /api/v1/access-requests":
		return true, true
	case "POST /api/v1/access-requests/:id/cancel":
		return true, true
	case "GET /api/v1/access-requests/:id/reports":
		return true, true
	case "POST /api/v1/access-requests/:id/reports":
		return true, true
	case "GET /api/v1/agent-tool-calls":
		return false, true
	case "POST /api/v1/users/:id/agent-breaker/release":
		return false, true
	case "POST /api/v1/mcp":
		return true, true
	case "DELETE /api/v1/alert-rules/:id":
		return false, true
	case "DELETE /api/v1/approver-scopes/:id":
		return false, true
	case "DELETE /api/v1/asset-groups/:id":
		return false, true
	case "DELETE /api/v1/assets/:id":
		return false, true
	case "DELETE /api/v1/assets/:id/accounts/:accountId":
		return false, true
	case "DELETE /api/v1/assets/:id/files":
		return false, true
	case "DELETE /api/v1/assets/:id/host-key":
		return false, true
	case "DELETE /api/v1/authorizations/:id":
		return false, true
	case "DELETE /api/v1/change-secret-candidates/:id":
		return false, true
	case "DELETE /api/v1/change-secret-plans/:id":
		return false, true
	case "DELETE /api/v1/credentials/:id":
		return false, true
	case "DELETE /api/v1/credentials/:id/bindings/:accountId":
		return false, true
	case "DELETE /api/v1/identity-sources/:type/:sourceId/mappings/:ruleId":
		return false, true
	case "DELETE /api/v1/keys/retired-material":
		return false, true
	case "DELETE /api/v1/keys/rewrap":
		return false, true
	case "DELETE /api/v1/ldap-directory":
		return false, true
	case "DELETE /api/v1/notification-channels/:id":
		return false, true
	case "DELETE /api/v1/oidc-providers/:id":
		return false, true
	case "DELETE /api/v1/policy-groups/:code":
		return false, true
	case "DELETE /api/v1/policy-groups/:code/clauses/:clause_no":
		return false, true
	case "DELETE /api/v1/rotation-report/schedules/:id":
		return false, true
	case "DELETE /api/v1/sessions/:id/recording":
		return false, true
	case "DELETE /api/v1/sessions/:id/share":
		return false, true
	case "DELETE /api/v1/snippets/:id":
		return false, true
	case "DELETE /api/v1/user-groups/:id":
		return false, true
	case "DELETE /api/v1/users/:id":
		return false, true
	case "DELETE /api/v1/users/:id/agent-tokens/:tokenId":
		return false, true
	case "DELETE /api/v1/users/:id/external-identities/:identityId":
		return false, true
	case "GET /api/v1/access-requests/history":
		return false, true
	case "GET /api/v1/access-requests/pending":
		return false, true
	case "GET /api/v1/access-requests/pending/count":
		return false, true
	case "GET /api/v1/access-requests/reviews/pending":
		return false, true
	case "GET /api/v1/access-requests/tickets":
		return false, true
	case "GET /api/v1/access-reviews":
		return false, true
	case "GET /api/v1/access-reviews/:id":
		return false, true
	case "GET /api/v1/access-reviews/matrix":
		return false, true
	case "GET /api/v1/alert-rules":
		return false, true
	case "GET /api/v1/approver-scopes":
		return false, true
	case "GET /api/v1/asset-groups":
		return false, true
	case "GET /api/v1/asset-groups/tree":
		return false, true
	case "GET /api/v1/assets/:id/files":
		return false, true
	case "GET /api/v1/assets/:id/files/download":
		return false, true
	case "GET /api/v1/assets/:id/host-key":
		return false, true
	case "GET /api/v1/assets/:id/k8s/download":
		return false, true
	case "GET /api/v1/assets/:id/transfer-capabilities":
		return false, true
	case "GET /api/v1/audit-checkpoints":
		return false, true
	case "GET /api/v1/audit-checkpoints/public-key":
		return false, true
	case "GET /api/v1/audit-checkpoints/verify":
		return false, true
	case "GET /api/v1/audit-export":
		return false, true
	case "GET /api/v1/audit-export/jobs":
		return false, true
	case "GET /api/v1/audit-export/jobs/:id/download":
		return false, true
	case "GET /api/v1/audit-export/public-key":
		return false, true
	case "GET /api/v1/audit-failures":
		return false, true
	case "GET /api/v1/audit-integrity/verify":
		return false, true
	case "GET /api/v1/audit-logs":
		return false, true
	case "GET /api/v1/audit-logs/:id":
		return false, true
	case "GET /api/v1/audit-logs/resource/:resource/:id":
		return false, true
	case "GET /api/v1/audit/subjects":
		return false, true
	case "GET /api/v1/audit/timeline":
		return false, true
	case "GET /api/v1/auth/banner":
		return false, true
	case "GET /api/v1/auth/me":
		return false, true
	case "GET /api/v1/auth/methods":
		return false, true
	case "GET /api/v1/auth/oidc/:id/begin":
		return false, true
	case "GET /api/v1/auth/oidc/callback":
		return false, true
	case "GET /api/v1/authorizations":
		return false, true
	case "GET /api/v1/authorizations/effective-assets":
		return false, true
	case "GET /api/v1/authorizations/effective-users":
		return false, true
	case "GET /api/v1/change-secret-batches":
		return false, true
	case "GET /api/v1/change-secret-batches/:id":
		return false, true
	case "GET /api/v1/change-secret-batches/targets":
		return false, true
	case "GET /api/v1/change-secret-batches/usernames":
		return false, true
	case "GET /api/v1/change-secret-candidates":
		return false, true
	case "GET /api/v1/change-secret-plans":
		return false, true
	case "GET /api/v1/change-secret-plans/:id/records":
		return false, true
	case "GET /api/v1/command-alerts":
		return false, true
	case "GET /api/v1/commands":
		return false, true
	case "GET /api/v1/compliance/snapshot":
		return false, true
	case "GET /api/v1/connect":
		return false, true
	case "GET /api/v1/credentials":
		return false, true
	case "GET /api/v1/credentials/:id":
		return false, true
	case "GET /api/v1/credentials/:id/rotations/:rid":
		return false, true
	case "GET /api/v1/daily-reviews":
		return false, true
	case "GET /api/v1/daily-reviews/status":
		return false, true
	case "GET /api/v1/db-console":
		return false, true
	case "GET /api/v1/db-console/sessions/:id/results/:event_id/export":
		return false, true
	case "GET /api/v1/identity-sources":
		return false, true
	case "GET /api/v1/identity-sources/:type/:sourceId/mappings":
		return false, true
	case "GET /api/v1/instance-guard":
		return false, true
	case "GET /api/v1/instance-guard/halt":
		return false, true
	case "GET /api/v1/keys":
		return false, true
	case "GET /api/v1/keys/topology":
		return false, true
	case "GET /api/v1/ldap-directory":
		return false, true
	case "GET /api/v1/ldap-directory/status":
		return false, true
	case "GET /api/v1/notification-channels":
		return false, true
	case "GET /api/v1/offsite-storage/failures":
		return false, true
	case "GET /api/v1/offsite-storage/profiles":
		return false, true
	case "GET /api/v1/offsite-storage/settings":
		return false, true
	case "GET /api/v1/offsite-storage/status":
		return false, true
	case "GET /api/v1/oidc-providers":
		return false, true
	case "GET /api/v1/oidc-providers/:id":
		return false, true
	case "GET /api/v1/oidc-providers/:id/status":
		return false, true
	case "GET /api/v1/ping":
		return false, true
	case "GET /api/v1/policy-groups":
		return false, true
	case "GET /api/v1/policy-groups/:code":
		return false, true
	case "GET /api/v1/recordings/stats":
		return false, true
	case "GET /api/v1/recordings/stream":
		return false, true
	case "GET /api/v1/roles":
		return false, true
	case "GET /api/v1/rotation-report":
		return false, true
	case "GET /api/v1/rotation-report/records":
		return false, true
	case "GET /api/v1/rotation-report/schedules":
		return false, true
	case "GET /api/v1/seal/status":
		return false, true
	case "GET /api/v1/security-policies":
		return false, true
	case "GET /api/v1/security-policies/defs/:key":
		return false, true
	case "GET /api/v1/sessions":
		return false, true
	case "GET /api/v1/sessions/:id":
		return false, true
	case "GET /api/v1/sessions/:id/clipboard-events":
		return false, true
	case "GET /api/v1/sessions/:id/clipboard-events/:eventID/content":
		return false, true
	case "GET /api/v1/sessions/:id/commands":
		return false, true
	case "GET /api/v1/sessions/:id/monitor":
		return false, true
	case "GET /api/v1/sessions/:id/recording":
		return false, true
	case "GET /api/v1/sessions/:id/recording/download":
		return false, true
	case "GET /api/v1/sessions/:id/recording/stream":
		return false, true
	case "GET /api/v1/sessions/active":
		return false, true
	case "GET /api/v1/sessions/share/:code/ws":
		return false, true
	case "GET /api/v1/sessions/statistics":
		return false, true
	case "GET /api/v1/snippets":
		return false, true
	case "GET /api/v1/ssh":
		return false, true
	case "GET /api/v1/ssh/sessions/:id/stats":
		return false, true
	case "GET /api/v1/syslog-settings":
		return false, true
	case "GET /api/v1/transmission-inventory":
		return false, true
	case "GET /api/v1/user-groups":
		return false, true
	case "GET /api/v1/user-groups/:id/authorization-count":
		return false, true
	case "GET /api/v1/users":
		return false, true
	case "GET /api/v1/users/:id":
		return false, true
	case "GET /api/v1/users/:id/agent-tokens":
		return false, true
	case "GET /api/v1/users/:id/external-identities":
		return false, true
	case "GET /api/v1/users/local-admin-count":
		return false, true
	case "GET /health":
		return false, true
	case "GET /healthz":
		return false, true
	case "GET /metrics":
		return false, true
	case "PATCH /api/v1/auth/me":
		return false, true
	case "POST /api/v1/access-requests/:id/approve":
		return false, true
	case "POST /api/v1/access-requests/:id/reject":
		return false, true
	case "POST /api/v1/access-requests/:id/review":
		return false, true
	case "POST /api/v1/access-requests/:id/revoke":
		return false, true
	case "POST /api/v1/access-requests/break-glass":
		return false, true
	case "POST /api/v1/access-reviews":
		return false, true
	case "POST /api/v1/alert-rules":
		return false, true
	case "POST /api/v1/approver-scopes":
		return false, true
	case "POST /api/v1/asset-groups":
		return false, true
	case "POST /api/v1/assets":
		return false, true
	case "POST /api/v1/assets/:id/accounts":
		return false, true
	case "POST /api/v1/assets/:id/accounts/:accountId/set-default":
		return false, true
	case "POST /api/v1/assets/:id/files/mkdir":
		return false, true
	case "POST /api/v1/assets/:id/files/upload":
		return false, true
	case "POST /api/v1/assets/:id/k8s/upload":
		return false, true
	case "POST /api/v1/assets/:id/test-connection":
		return false, true
	case "POST /api/v1/assets/tags/delete":
		return false, true
	case "POST /api/v1/assets/tags/rename":
		return false, true
	case "POST /api/v1/audit-export/jobs":
		return false, true
	case "POST /api/v1/auth/change-password":
		return false, true
	case "POST /api/v1/auth/login":
		return false, true
	case "POST /api/v1/auth/logout":
		return false, true
	case "POST /api/v1/auth/mfa/disable":
		return false, true
	case "POST /api/v1/auth/mfa/enable":
		return false, true
	case "POST /api/v1/auth/mfa/enroll/confirm":
		return false, true
	case "POST /api/v1/auth/mfa/enroll/setup":
		return false, true
	case "POST /api/v1/auth/mfa/setup":
		return false, true
	case "POST /api/v1/auth/mfa/verify":
		return false, true
	case "POST /api/v1/auth/oidc/exchange":
		return false, true
	case "POST /api/v1/auth/refresh":
		return false, true
	case "POST /api/v1/authorizations":
		return false, true
	case "POST /api/v1/authorizations/batch":
		return false, true
	case "POST /api/v1/change-secret-batches":
		return false, true
	case "POST /api/v1/change-secret-candidates/:id/retry":
		return false, true
	case "POST /api/v1/change-secret-plans":
		return false, true
	case "POST /api/v1/change-secret-plans/:id/run":
		return false, true
	case "POST /api/v1/command-alerts/:id/review":
		return false, true
	case "POST /api/v1/connect-tokens":
		return false, true
	case "POST /api/v1/credentials":
		return false, true
	case "POST /api/v1/credentials/:id/bindings":
		return false, true
	case "POST /api/v1/credentials/:id/bindings/:accountId/detach":
		return false, true
	case "POST /api/v1/credentials/:id/rotations":
		return false, true
	case "POST /api/v1/credentials/:id/rotations/:rid/abandon":
		return false, true
	case "POST /api/v1/credentials/:id/rotations/:rid/members/:mid/retry":
		return false, true
	case "POST /api/v1/credentials/:id/scope":
		return false, true
	case "POST /api/v1/credentials/:id/secret":
		return false, true
	case "POST /api/v1/daily-reviews":
		return false, true
	case "POST /api/v1/identity-sources/:type/:sourceId/mappings":
		return false, true
	case "POST /api/v1/instance-guard/ack":
		return false, true
	case "POST /api/v1/keys/rewrap":
		return false, true
	case "POST /api/v1/keys/rotate":
		return false, true
	case "POST /api/v1/ldap-directory/test":
		return false, true
	case "POST /api/v1/my/connections/:id/terminate":
		return false, true
	case "POST /api/v1/notification-channels":
		return false, true
	case "POST /api/v1/notification-channels/:id/test":
		return false, true
	case "POST /api/v1/offsite-storage/objects/:id/retry":
		return false, true
	case "POST /api/v1/offsite-storage/profiles/:id/revoke-credentials":
		return false, true
	case "POST /api/v1/offsite-storage/retry-failed":
		return false, true
	case "POST /api/v1/offsite-storage/settings/confirm":
		return false, true
	case "POST /api/v1/offsite-storage/settings/disable":
		return false, true
	case "POST /api/v1/offsite-storage/test":
		return false, true
	case "POST /api/v1/oidc-providers":
		return false, true
	case "POST /api/v1/oidc-providers/discovery-preview":
		return false, true
	case "POST /api/v1/policy-groups":
		return false, true
	case "POST /api/v1/policy-groups/:code/clauses/:clause_no/confirm":
		return false, true
	case "POST /api/v1/rotation-report/jobs":
		return false, true
	case "POST /api/v1/rotation-report/schedules":
		return false, true
	case "POST /api/v1/rotation-report/schedules/:id/run":
		return false, true
	case "POST /api/v1/schedules/next-runs":
		return false, true
	case "POST /api/v1/seal/authorize":
		return false, true
	case "POST /api/v1/seal/seal":
		return false, true
	case "POST /api/v1/seal/unseal":
		return false, true
	case "POST /api/v1/security-policies/apply-preview":
		return false, true
	case "POST /api/v1/security-policies/compliance/preview":
		return false, true
	case "POST /api/v1/sessions/:id/monitor-token":
		return false, true
	case "POST /api/v1/sessions/:id/recording/token":
		return false, true
	case "POST /api/v1/sessions/:id/share":
		return false, true
	case "POST /api/v1/sessions/:id/terminate":
		return false, true
	case "POST /api/v1/sessions/share/token":
		return false, true
	case "POST /api/v1/snippets":
		return false, true
	case "POST /api/v1/syslog-settings/test":
		return false, true
	case "POST /api/v1/transmission-consents":
		return false, true
	case "POST /api/v1/transmission-inventory/export":
		return false, true
	case "POST /api/v1/user-groups":
		return false, true
	case "POST /api/v1/users":
		return false, true
	case "POST /api/v1/users/:id/agent-tokens":
		return false, true
	case "POST /api/v1/users/:id/external-identities":
		return false, true
	case "POST /api/v1/users/:id/external-identities/:identityId/unbind-and-disable":
		return false, true
	case "POST /api/v1/users/:id/external-only":
		return false, true
	case "POST /api/v1/users/:id/mfa/disable":
		return false, true
	case "POST /api/v1/users/:id/roles/:role":
		return false, true
	case "POST /api/v1/users/:id/roles/pin":
		return false, true
	case "POST /api/v1/users/:id/unlock":
		return false, true
	case "POST /api/v1/users/source-policy/check":
		return false, true
	case "POST /health":
		return false, true
	case "PUT /api/v1/alert-rules/:id":
		return false, true
	case "PUT /api/v1/asset-groups/:id":
		return false, true
	case "PUT /api/v1/asset-groups/:id/move":
		return false, true
	case "PUT /api/v1/assets/:id":
		return false, true
	case "PUT /api/v1/assets/:id/accounts/:accountId":
		return false, true
	case "PUT /api/v1/assets/:id/accounts/:accountId/credential":
		return false, true
	case "PUT /api/v1/authorizations/:id/accounts":
		return false, true
	case "PUT /api/v1/change-secret-plans/:id":
		return false, true
	case "PUT /api/v1/credentials/:id":
		return false, true
	case "PUT /api/v1/identity-sources/:type/:sourceId/mappings/:ruleId":
		return false, true
	case "PUT /api/v1/keys/topology":
		return false, true
	case "PUT /api/v1/ldap-directory":
		return false, true
	case "PUT /api/v1/notification-channels/:id":
		return false, true
	case "PUT /api/v1/offsite-storage/settings":
		return false, true
	case "PUT /api/v1/oidc-providers/:id":
		return false, true
	case "PUT /api/v1/policy-groups/:code":
		return false, true
	case "PUT /api/v1/policy-groups/:code/clauses/:clause_no":
		return false, true
	case "PUT /api/v1/policy-groups/:code/clauses/:clause_no/annotation":
		return false, true
	case "PUT /api/v1/policy-groups/:code/enabled":
		return false, true
	case "PUT /api/v1/rotation-report/schedules/:id":
		return false, true
	case "PUT /api/v1/security-policies":
		return false, true
	case "PUT /api/v1/snippets/:id":
		return false, true
	case "PUT /api/v1/syslog-settings":
		return false, true
	case "PUT /api/v1/user-groups/:id":
		return false, true
	case "PUT /api/v1/user-groups/:id/members":
		return false, true
	case "PUT /api/v1/users/:id":
		return false, true
	case "PUT /api/v1/users/:id/inactivity-exempt":
		return false, true
	case "PUT /api/v1/users/:id/password":
		return false, true
	case "PUT /api/v1/users/:id/roles":
		return false, true
	case "PUT /api/v1/users/:id/status":
		return false, true
	default:
		return false, false
	}
}
